fetch("data-logo.csv").then(t=>{if(!t.ok){throw new Error("fetch時http錯誤："+t.status)}return t.text()}).then(t=>csvToJson(t)).then(t=>initBuildLogo(t)).catch(t=>{throw new Error("本機端fetch失敗："+t)});function initBuildLogo(t){buildTabHead(t);buildTabBody(t);addTabClick();document.querySelectorAll(".jsTabItem")[0].click()}function buildTabBody(t){t.sort((t,e)=>{let o=/[a-zA-Z0-9]/;if(o.test(t["品牌名稱"])||o.test(e["品牌名稱"])){if(t["品牌名稱"]>e["品牌名稱"])return 1;else if(t["品牌名稱"]<["品牌名稱"])return-1;else return 0}else return t["品牌名稱"].localeCompare(e["品牌名稱"])});t.sort((t,e)=>t["注音"].localeCompare(e["注音"]));const e=sortTitle(t);buildTabItem(t,e);buildSortItem(e)}function buildTabHead(t){const n=[];let e=[];const i=document.getElementById("tabHead");t.forEach((t,e,o)=>{n.push(t["分類"])});e=n.filter((t,e,o)=>{return o.indexOf(t)===e});e.forEach((t,e)=>{const o=`<div class="jsTabItem tab__item tab--${e+1}">
        <div class="tab__pic">
          <img src="tabs/tab-${e+1}.png" alt="${t}">
          <img src="tabs/tab-${e+1}-active.png" alt="${t}">
        </div>
        <div class="tab__text">${t}</div>
      </div>`;i.insertAdjacentHTML("beforeend",o)})}function sortTitle(t){const o=[];let e=[];t.forEach((t,e)=>{o.push(t["注音"])});e=o.filter((t,e,o)=>{return o.indexOf(t)===e});return e}function buildTabItem(t,l){const s=document.getElementById("tabBody");let c;let r=0;t.forEach((i,t)=>{l.forEach((t,e)=>{if(i["注音"]===t&&c!==e){const o=l[e]===""?defaultTitleName?defaultTitleName:"#":l[e];const n=`<h2 id="${o}">${o}</h2>`;s.insertAdjacentHTML("beforeend",n);c=e;r=e}});const e=isApp()?i["品牌旗艦館APP連結"]:i["品牌旗艦館連結"];const o=`<div class="jsTabContent tab__content content--${t+1} title--${r+1}" data-cht="${i["注音"]}" data-group="${i["分類"]}">
        <a href="${e}" title="${i["品牌名稱"]}">
        <div class="tab__pic">
          <img class="pic--web" src="${i["大網LOGO"]}" alt="${i["品牌名稱"]}">
        </div>
        <div class="tab__text">${i["品牌名稱"]}</div>
      </div>`;s.insertAdjacentHTML("beforeend",o)})}function buildSortItem(t){const s=document.getElementById("sortWrap");t.forEach((t,e)=>{const o=sortNavShowLimit?sortNavShowLimit:3;if(t==="")t=defaultTitleName?defaultTitleName:"#";const n=".title--"+(e+1);const i=document.querySelectorAll(n).length;if(i>=o){const l=`<a href="#${t}" class="jsSortItem sort__item" title="${t}">${t}</div>`;s.insertAdjacentHTML("beforeend",l)}})}function moveActiveToItem(t,e,o="active"){t.forEach(t=>t.classList.remove(o));t[e].classList.add(o)}function addTabClick(){const t=Array.apply(null,document.querySelectorAll(".jsTabItem"));t.forEach((t,e,o)=>{t.addEventListener("click",()=>{moveActiveToItem(o,e);tabContentsFilter(t);removeAllHideTitle()})})}function tabContentsFilter(n){const t=Array.apply(null,document.querySelectorAll(".jsTabContent"));let i;t.forEach(t=>{t.classList.add("hide");const e=n.querySelector(".tab__text").innerText;if(e==="全部品牌"){t.classList.remove("hide");const o=t.querySelector(".tab__text").innerText;if(o!==i){i=o}else{t.classList.add("hide")}}else if(t.dataset.group===e){t.classList.remove("hide")}})}function removeAllHideTitle(){const t=Array.apply(null,document.querySelectorAll("#tabBody h2"));t.forEach((t,e,o)=>{t.classList.remove("hide");const n=".title--"+(e+1);const i=document.querySelectorAll(n);const l=".title--"+(e+1)+".hide";const s=document.querySelectorAll(l);if(s.length-i.length===0){o[e].classList.add("hide")}});removeAllHideSortItem()}function removeAllHideSortItem(){const t=Array.apply(null,document.querySelectorAll(".jsSortItem"));const e=Array.apply(null,document.querySelectorAll("#tabBody h2"));t.forEach(t=>{t.classList.remove("hide")});e.forEach(e=>{if(e.classList.contains("hide")){t.forEach(t=>{if(t.innerText===e.innerText){t.classList.add("hide")}})}})}function csvToJson(t){const e=t.split(/\n/g);const i=e.shift().split(",");const l=[];e.forEach(t=>{const o=t.split(",");const n={};i.forEach((t,e)=>{n[t]=o[e]});l.push(n)});return l}function isApp(){const t=/(WebView|(iPhone|iPod|iPad)(?!.*Safari\/)(?!.*Line\/)|Android.*(wv|.0.0.0))(?!.*Line\/)/gi.test(navigator.userAgent);if(t)return true;else return false}